[[redirects]]
  from = "/api/*"
  to = "https://mindpilot-backend-production.up.railway.app/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/reports/:id"
  to = "https://mindpilot-backend-production.up.railway.app/report/:id"
  status = 200
  force = true

[[redirects]]
  from = "/social/:id"
  to = "https://mindpilot-backend-production.up.railway.app/social/:id"
  status = 200
  force = true
